### ISSUE TITLE
Position for Persons is not correct

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/EELISA-research-object#3]
Right now if a person has had two positions, the JSON-LD reads: 
```
position:  "Universidad Politécnica de Madrid \| University of Southern California"
```
However, there should be two "position" fields, each with its respective value.

**Comment by PavelAntonia** [comment]
Now it is constructed like this:
"position": [
                "Universidad Politécnica de Madrid",
                "University of Southern California"
            ]
Is this okay?

**Comment by dgarijo** [comment]
Yes, this should be ok.
